### PR TITLE
Fix message signing function

### LINKED ISSUE #234: Incorrect signature created by Elixir library
Hey!

I really appreciate an effort to create a standard around Webhook handling.

1. Yesterday, I was looking into an Elixir library to create a signature for webhook. I was comparing results between an interface to verify Webhooks signature: https://www.standardwebhooks.com/verify and library code.

I couldn't get it working, until I've made changes to the function responsible for creating a signature. Based on reading some issues and PRs, it appeared to me, that `secret` needs to be a Base64 encoded string.

```elixir
  defp sign_and_encode(to_sign, secret) do
    :crypto.mac(:hmac, :sha256, Base.decode64!(secret), to_sign)
    |> Base.encode64()
    |> String.trim()
  end
```

After that, I was able to get matching results:

Image

I'm going to make a PR to fix this issue.

2. Are there any plans to publish an Elixir library to the Hex repository? I saw a library for Webhook handling: https://hexdocs.pm/webhoox/readme.html, but it seems to cover much bigger scope than Standard Webhooks. It would be great to have a library limited to just Standard Webhooks. Is there any way, I can contribute to as an Elixir developer to publish it?

### PR DESCRIPTION
**Pull request by kevinam99**
Aims to fix #234

### CODE REVIEW

File: libraries/elixir/lib/standard_webhooks.ex [hunk 1]
```diff
@@ -124,7 +124,7 @@ defmodule StandardWebhooks do
   end
 
   defp sign_and_encode(to_sign, secret) do
-    :crypto.mac(:hmac, :sha256, secret, to_sign)
+    :crypto.mac(:hmac, :sha256, Base.decode64!(secret), to_sign)
```
Comment (tasn) [inline libraries/elixir/lib/standard_webhooks.ex:127]: Thanks a lot for the PR!

There's another small bug in this code, can you potentially fix that too? It should also strip the `whsec_` prefix if one exists. E.g. see the JavaScript code: https://github.com/standard-webhooks/standard-webhooks/blob/main/libraries/javascript/src/index.ts#L52-L55

Comment (kevinam99) [reply libraries/elixir/lib/standard_webhooks.ex:127]: Thanks for the suggestion! Yes, I realised that this is an issue when I ran tests. Will push a fix

Comment (kevinam99) [reply libraries/elixir/lib/standard_webhooks.ex:133]: Done!

**Review by tasn — APPROVED** [review]
Thank you!

**Comment by kevinam99** [comment]
More than happy to help :)
